services:
  - type: web
    name: portfolio-site
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    autoDeploy: true
    envVars:
      - key: SESSION_SECRET
        value: "change-this-in-production"
